package apps.app_campeonatum;

import libs.entt.ENTT;
import libs.entt.Entidade;
import libs.luan.Lista;

public class C12 {

    private Lista<Entidade> mDados;

    public C12() {

        mDados = new Lista<Entidade>();

        carregar();

    }

    public Lista<String> GET_TIMES() {
        return ENTT.FILTRAR_UNICOS(mDados, "Time");
    }


    public Lista<Entidade> getDados() {
        return mDados;
    }


    private void CRIAR_JOGADOR(String eTime, String eNome, String eFuncao) {

        Entidade e = ENTT.CRIAR("Time", eTime);
        e.at("Nome", eNome);
        e.at("Funcao", eFuncao);

        mDados.adicionar(e);
    }

    private void carregar() {

        CRIAR_JOGADOR("Imfaz", "Sollo Parempa Zalrezneguo", "TREINADOR");
        CRIAR_JOGADOR("Imfaz", "Pazpazpazrem de Fazma", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Dimpazmeshrez Grate", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Tomdimdimra Grazalxira Guedocgacol", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Tomtommeshrem de Nefaz", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Tomsolgra de Xiga Gracolxi", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Sollo Fazzal Vama", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Tompazga Grafaztega Palamox", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Tomsoldimdoc de Moxgagama", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Soldimtomzal de Fazne", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Pazdimpazga de Lama", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Meshrem de Lacolra Nevafazfaz", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Solgue Gradocremzal", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Pazmazdimxi de Temoxrate", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Solsoldimrem de Paremlate", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Mazsolmazla de Rezxigue", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Tomxi de Zalzal", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Mazxi Laguo Xiguo", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Maztomlo Lafaz Rala", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Dimga Gagraxidoc Garane", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Dimdoc de Tegue", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Tommazmazpa Magazalfaz Loxi", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Dimtomsolga de Gazalpa Xigue", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Pazga Mararadoc Nemoxva", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Solmox de Necol Raxicol", "JOGADOR");
        CRIAR_JOGADOR("Imfaz", "Pazdimpa Xidou", "MÉDICO");
        CRIAR_JOGADOR("Imfaz", "Tomguo Mara Vacolguoguo", "MÉDICO");
        CRIAR_JOGADOR("Imfaz", "Mazmeshdimte Douzal", "MÉDICO");
        CRIAR_JOGADOR("Imfaz", "Tomsolmazrez de Moxzallo", "MÉDICO");
        CRIAR_JOGADOR("Imfaz", "Meshmeshgra Xizal", "MÉDICO");
        CRIAR_JOGADOR("Dimma", "Pazsolguo Gatedoc", "TREINADOR");
        CRIAR_JOGADOR("Dimma", "Tomsoldimma Doczalmox Maradoc", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Solmeshsolgra Rezrezne", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Mazmox Rezgala", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Pazdimtomgra de Razal Guolaremrem", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Pazmeshdimrez de Guotetedou Raracoldoc", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Tomxi Tepa Doudoudocne", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Solgra Docteradou", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Dimmox de Logralafaz", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Meshtommazpa de Tedocmox Docgraga", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Pazmeshsolrez de Remlo", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Maztomguo Zalvadocra Nefazguo", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Pazdimtomma de Pague Marezdocte", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Mazmazva Zalrezzaldou", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Meshzal de Zalxirezva Zalfaz", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Meshmeshsolte Neguega", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Pazma de Guezalgrala Moxpacol", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Pazpazpazrem Palograla Tezal", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Soldimdimgue de Loxima Paguoma", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Meshmeshsolrez Gaguepa Fazlara", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Dimdimlo de Neguo Madocvaga", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Meshcol de Zalma Rezvagra", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Solla Gracol Lague", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Mazsolpazcol Tedoumox Guefaznelo", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Soltomne de Doumox Zaldocguolo", "JOGADOR");
        CRIAR_JOGADOR("Dimma", "Meshmeshmeshla de Guolola Lanedocla", "MÉDICO");
        CRIAR_JOGADOR("Dimma", "Meshumzmox Gadocmox Guoremdocdou", "MÉDICO");
        CRIAR_JOGADOR("Dimma", "Pazmazpazla Moxfaz Lafaz", "MÉDICO");
        CRIAR_JOGADOR("Dimma", "Pazfaz de Colguo", "MÉDICO");
        CRIAR_JOGADOR("Dimma", "Maztommazpa de Vanevane", "MÉDICO");
        CRIAR_JOGADOR("Pazdou", "Solpazpazguo Docnedocrem Rezgradou", "TREINADOR");
        CRIAR_JOGADOR("Pazdou", "Tommeshdimgra Ratecolte Moxtedoura", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Meshdimpazte de Neva", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Meshmaztomma Valo Colguoga", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Tomdimtomxi Fazvaxi Mazalla", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Meshdimsolgue de Remga Tegarem", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Soltomsolgra de Gacolcolgue Grane", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Solcol Varezla Nene", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Pazne de Rava", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Dimtomdimmox de Tezal", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Meshrez Docguo", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Soldimsolgra Gueparadou", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Dimxi Mamoxtegue Vamoxvalo", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Solmeshla Zalfaz", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Tommeshcol Lamoxlodou Lolomox", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Pazguo de Moxdouva Paloguone", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Meshdimcol Rezloxiva Zaltecolcol", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Mazmazla Maralorez", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Dimxi de Gracol Tecolxigue", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Dimma de Docremguo Guedocla", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Mazpazmeshxi de Zalte", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Solte de Moxpadoc", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Meshguo de Pamadoufaz", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Meshmeshdimva Radoulo Nerate", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Meshsolma de Moxlo", "JOGADOR");
        CRIAR_JOGADOR("Pazdou", "Dimsolpazte Colgueraxi", "MÉDICO");
        CRIAR_JOGADOR("Pazdou", "Dimsollo de Galorez Doute", "MÉDICO");
        CRIAR_JOGADOR("Pazdou", "Solgue Lopanedoc Fazremzal", "MÉDICO");
        CRIAR_JOGADOR("Pazdou", "Mazdimmazga Nemalozal Fazmazal", "MÉDICO");
        CRIAR_JOGADOR("Pazdou", "Tommazfaz de Guetema", "MÉDICO");
        CRIAR_JOGADOR("Silmla", "Pazmazmeshlo de Pagra Zalloremla", "TREINADOR");
        CRIAR_JOGADOR("Silmla", "Mazmazmazpa de Zalfaz", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Meshlo de Zalmaguopa", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Meshtommeshmox Mafaz Lola", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Meshmeshmeshzal de Gramoxrem Fazdoc", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Mazpaztomgue Remte Tetegue", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Tompazpazla Rezpalala", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Meshrez de Doutetema Rezguofaz", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Mazte Lozallo Colremva", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Meshsolpazte Zalzallova Ramox", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Meshmeshma Gazalgue Gadoc", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Meshpazdoc de Gagra", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Solxi Guetera Gafazgrane", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Mazlo de Colmarezgue Mafazzal", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Pazva de Tedoune", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Meshgra de Zalrez", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Dimra de Remmarane Docdouxifaz", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Tomtomga de Gramamara Tevala", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Tommeshfaz de Mala", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Meshdou de Vamox Gueguorala", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Dimdimcol de Pagueguo Xine", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Solpazmeshgue Docparama Guomox", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Mazte Loguo", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Paztomfaz de Teravane", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Meshdimcol de Colgaxi Gadou", "JOGADOR");
        CRIAR_JOGADOR("Silmla", "Solne de Lazal Rezpa", "MÉDICO");
        CRIAR_JOGADOR("Silmla", "Solmazgue Gaxi", "MÉDICO");
        CRIAR_JOGADOR("Silmla", "Soltomfaz de Douremrezma Magueparez", "MÉDICO");
        CRIAR_JOGADOR("Silmla", "Mazmaztomcol Fazva", "MÉDICO");
        CRIAR_JOGADOR("Silmla", "Tomtomdimlo Gapa", "MÉDICO");
        CRIAR_JOGADOR("Meshga", "Mazpazzal de Lopamox Vara", "TREINADOR");
        CRIAR_JOGADOR("Meshga", "Tomga de Rate", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Mazdimmazga Gadoclo Docvalague", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Dimfaz de Gralogadou", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Meshla de Rezfaz Guodoctedoc", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Paztomtomrem Ladocguo Doufazga", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Dimmeshrez Docrezne Remga", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Mazpazrem de Lazal", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Pazdimtommox de Gazalzalrem", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Tommazmazra Guefazdocxi", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Pazlo de Grarez", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Dimdimma Pamoxlo Rempaga", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Solguo de Lorezdourez", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Solmazdimte de Graremdocgra", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Dimtomgra de Guomarem", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Mazxi de Larezla", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Dimlo de Fazmadougue Palo", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Meshtomte Vamagra", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Sollo de Nenera Magrazal", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Solma Moxloxima", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Mazmazgue de Padoularem Neguelone", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Mazlo Guegaguela Lomoxguova", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Tommeshguo Neremgama Fazzalterem", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Pazsolpazva de Nemoxmoxma", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Meshtomsolga Rezcolxigra Zalmapa", "JOGADOR");
        CRIAR_JOGADOR("Meshga", "Pazdimguo Ralamalo", "MÉDICO");
        CRIAR_JOGADOR("Meshga", "Solmeshdou Palapa Grarezrem", "MÉDICO");
        CRIAR_JOGADOR("Meshga", "Meshla de Loma", "MÉDICO");
        CRIAR_JOGADOR("Meshga", "Pazmeshrem Zallo", "MÉDICO");
        CRIAR_JOGADOR("Meshga", "Solmazlo Magraxi", "MÉDICO");
        CRIAR_JOGADOR("Pazdim", "Dimtommazrez Remrezrezma Terezlarem", "TREINADOR");
        CRIAR_JOGADOR("Pazdim", "Mazga de Colmara Xigue", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Soldimmox Vamamoxrez", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Tommeshcol de Guoguoraxi Fazmague", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Dimma Reztema Grazalguoxi", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Pazva de Raguomox", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Meshga Rezdou", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Dimmeshdoc de Guemox Docrez", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Dimpazmeshma Rezne", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Dimtommeshpa de Panedouxi", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Soltompa de Zalpamox Guorezguo", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Dimne de Remxigrarem Guedocguete", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Dimfaz Vagra", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Pazdimguo Guerem Paguoxine", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Meshpa de Ladou Zalfaz", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Tomra de Madoc Nerezrem", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Dimtomte Loragueguo Varemdou", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Pazne Dounedouguo", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Pazsolne de Mara Ramoxte", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Mazga de Lagramazal Doufaz", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Pazpazzal de Lodoufaz Tegradoczal", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Pazmeshguo Vavala", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Tommazmox de Vaximoxgra Docte", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Mazmazgue de Lapafaz Remlocol", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Solla Mamoxmox", "JOGADOR");
        CRIAR_JOGADOR("Pazdim", "Tomrez de Remcolfazga Mava", "MÉDICO");
        CRIAR_JOGADOR("Pazdim", "Solpazzal Doune Zalgra", "MÉDICO");
        CRIAR_JOGADOR("Pazdim", "Pazmeshmazra de Loguorez", "MÉDICO");
        CRIAR_JOGADOR("Pazdim", "Solfaz de Xilovadou Grama", "MÉDICO");
        CRIAR_JOGADOR("Pazdim", "Mazzal de Neguenerez Docga", "MÉDICO");
        CRIAR_JOGADOR("Auzquem", "Mazdoc de Docdoc", "TREINADOR");
        CRIAR_JOGADOR("Auzquem", "Dimfaz de Colrez Moxpaguozal", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Solsolma de Guezal", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Dimmeshmazdoc Vaguo Docvague", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Qoota de Gava Remrara", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Pazpa de Colgueremte", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Solma Racol", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Dimgra de Fazzalmoxzal Larem", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Meshguo de Colfazdoclo Xirezgalo", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Dimtomdoc Docmoxmarez Moxtecolne", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Dimmeshdimne Remra", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Tomsolma de Gadou", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Tommeshtomlo Fazrez", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Maztommazrem de Tenete", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Mazra Guerezpava Colremcolguo", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Solmazdimzal de Neguecol Remva", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Tomtomra de Rezdourezmox Macolxirem", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Dimsoldoc de Magamoxgue Grarafazlo", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Dimgue de Rezrezvague", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Dimrez de Collategra Lagacol", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Solgue Lanezal", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Mazpazmeshguo de Guodoudoufaz Gaguo", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Mazmazgra Vara Ramox", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Dimdimsolcol de Lavadoc Fazparez", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Tommeshmazgra de Guopa Douracol", "JOGADOR");
        CRIAR_JOGADOR("Auzquem", "Pazgue Nedouzal", "MÉDICO");
        CRIAR_JOGADOR("Auzquem", "Solpazdimxi Docgra Colga", "MÉDICO");
        CRIAR_JOGADOR("Auzquem", "Meshmazmazrem Guemara Doccollapa", "MÉDICO");
        CRIAR_JOGADOR("Auzquem", "Tommaztomrem de Xifaz Zalguecolva", "MÉDICO");
        CRIAR_JOGADOR("Auzquem", "Maztomma de Temoxmalo", "MÉDICO");
        CRIAR_JOGADOR("Taqua", "Pazsolmeshrem Grara Guoxizalga", "TREINADOR");
        CRIAR_JOGADOR("Taqua", "Tomtomla de Gaguezalzal", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Meshtommeshra de Doucolfazra Xiraguoguo", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Meshdimdimte de Colfaz Tedocmadoc", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Sollo Parezpava Docxirem", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Pazpa Locol Rezcoldoc", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Mazsolrem de Douzalgate", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Pazpazmeshdou de Colremga Raga", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Mazdimcol de Moxpapara Lozalvadoc", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Tommox de Xira Xirama", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Meshmazmeshla Moxlomapa Docrezzal", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Pazpazsolguo Xila", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Mazpaztomra Xitevaxi Rezgracol", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Meshtomtomdoc Loguoremva", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Mazdoc Padocrez", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Pazdimmazmox Fazdounefaz", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Solmazxi Nedoufaz Docne", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Dimdimmazga de Gamox", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Solmeshla de Radocgrate", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Solxi de Pavama Guocolzal", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Solmazmeshla Maguolo", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Dimtomga Gueralo", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Pazpazdimlo Loremnega Guopagra", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Soldimtomva Necol", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Meshma de Vaguo Douremzalva", "JOGADOR");
        CRIAR_JOGADOR("Taqua", "Pazmazmeshte Moxdocla", "MÉDICO");
        CRIAR_JOGADOR("Taqua", "Pazdimsolcol Gaguo", "MÉDICO");
        CRIAR_JOGADOR("Taqua", "Solpazpa Docgranecol Xidouguo", "MÉDICO");
        CRIAR_JOGADOR("Taqua", "Tompa de Granegrate", "MÉDICO");
        CRIAR_JOGADOR("Taqua", "Meshum Rafazgra", "MÉDICO");
        CRIAR_JOGADOR("Solmox", "Solmeshdoc de Docguogrague Xilodoupa", "TREINADOR");
        CRIAR_JOGADOR("Solmox", "Pazdimrez de Moxfaz", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Mazmeshdou Ravatela Colcollarem", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Solzal de Rezzalmoxcol Tevamaguo", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Meshmeshma Lodoudou", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Dimmeshmazdoc Paxipaga Colgra", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Pazpazcol de Xizal", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Dimpazxi Nete", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Pazlo Xirez", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Dimva Guerem", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Pazva de Rezdoc", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Meshmeshfaz Faztedou Gazalrez", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Mazmazmazva de Gueguefazpa", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Mazmeshpazrem Guozaldoc Docma", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Meshmeshpazma Guelozal", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Meshpazmazte Remmoxgra", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Pazzal de Tegralacol Graparez", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Dimtomdimlo Xicol", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Dimmeshtomxi Guozalzalmox Grague", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Mazsolpazguo Mazal Guerem", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Pazdimgra Remnedou", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Meshmeshzal de Remdougama Lonegrara", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Dimdimra Razal", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Mazmox Xipanezal", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Pazne Gateva", "JOGADOR");
        CRIAR_JOGADOR("Solmox", "Meshmazfaz de Fazgra Nedoumox", "MÉDICO");
        CRIAR_JOGADOR("Solmox", "Meshgue Guezal Xidocgracol", "MÉDICO");
        CRIAR_JOGADOR("Solmox", "Mazsolsolva Xigue", "MÉDICO");
        CRIAR_JOGADOR("Solmox", "Tompazmazfaz Xigraguedoc Laguemox", "MÉDICO");
        CRIAR_JOGADOR("Solmox", "Meshtommeshma de Guogra", "MÉDICO");
        CRIAR_JOGADOR("Reffuz", "Mazdimpa Fazgue", "TREINADOR");
        CRIAR_JOGADOR("Reffuz", "Tomsoldimguo Nedou", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Pazdimte Gamox", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Solla Remgazalga", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Soltomsoldou de Moxdocxilo", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Pazpa Doulacolra", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Pazmeshra Rezcol", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Pazmazmazpa Fazguezal Padocguo", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Tomdimne de Vamoxraguo Douguodoc", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Tommazpazcol Maguemox Guedocfazfaz", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Dimfaz Doulo", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Pazmox de Vaguema Moxmarez", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Meshpazpazxi Ximox", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Mazmazsolmox de Guemoxguo", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Pazte Docgrague", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Dimmeshdimguo Rezxiguo Gradocpaga", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Pazsolpazzal Docnetecol", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Tommazga Lane Neradoc", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Pazsolgue Grara", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Pazga Lafaz", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Pazsolmeshrem Fazfaz", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Mazpazmeshgra Douvama", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Meshdimmeshzal de Remrez", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Paztomdoc de Remdocgue", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Tomsolsolpa Docva", "JOGADOR");
        CRIAR_JOGADOR("Reffuz", "Solmazte Rezgrarempa", "MÉDICO");
        CRIAR_JOGADOR("Reffuz", "Dimmox de Maximaguo", "MÉDICO");
        CRIAR_JOGADOR("Reffuz", "Mazsolsolrem Ragra Vadoc", "MÉDICO");
        CRIAR_JOGADOR("Reffuz", "Tommeshfaz de Docvapa", "MÉDICO");
        CRIAR_JOGADOR("Reffuz", "Pazpa de Palodoute Fazlo", "MÉDICO");
        CRIAR_JOGADOR("Azmeshu", "Pazsoldimcol de Ragraguomox", "TREINADOR");
        CRIAR_JOGADOR("Azmeshu", "Meshdimtomcol Guemaguete Papagrava", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Dimmazmeshdoc de Lorezcolla", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Meshma de Lama Zaldocdocmox", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Pazla de Negrarague", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Dimmeshpazguo de Varaguefaz", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Tomtomdimla de Graxi Guepa", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Dimmazsolne Rezxipate", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Dimcol de Paxi Graremdoczal", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Mazsoldou Logravalo Zalpague", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Dimpazsolmox de Xirem", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Meshpazsolmox de Nezalnecol", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Pazla Ragra Fazdoc", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Soltomsolla Ranema", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Dimma de Loremzalne Ladounepa", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Solpazmazgue de Lomava", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Mazpazmeshguo Xicol Xipaguorem", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Soldoc de Rama", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Tomdimmeshlo de Zalla", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Dimgra de Guoxi Gamamara", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Solpazmazguo de Pamox", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Paztommeshfaz Remdocla Fazremdoc", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Pazsolfaz de Nefazmox Loremcol", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Pazrez Colguomox", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Meshsoldimzal Moxguexi Fazdou", "JOGADOR");
        CRIAR_JOGADOR("Azmeshu", "Pazsoltomrem Guemox", "MÉDICO");
        CRIAR_JOGADOR("Azmeshu", "Tommeshmox de Valatefaz", "MÉDICO");
        CRIAR_JOGADOR("Azmeshu", "Tomgue Xiremcolga Palagafaz", "MÉDICO");
        CRIAR_JOGADOR("Azmeshu", "Tomdimzal de Vague Lofazdocte", "MÉDICO");
        CRIAR_JOGADOR("Azmeshu", "Pazdimtomla Docgue", "MÉDICO");
        CRIAR_JOGADOR("Meshum", "Tomtomla de Zalvaxi", "TREINADOR");
        CRIAR_JOGADOR("Meshum", "Meshmeshte de Rafaz Locolgava", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Paztomma Rezremne", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Dimxi Fazdou", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Solmazla Matepafaz Guoremlaga", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Dimdimpazdou de Douparemrez Lacolrezmox", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Pazdimmeshva Doclarem", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Pazzal de Rezzal Ladouguo", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Pazdimdimfaz Tepalo Zalralague", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Mazga Gamaguepa", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Meshmazgra de Colmafazlo", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Dimtomsolrem de Mate Douvazalla", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Dimpazmeshrem Moxxiva", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Tomsoldoc de Zaldou Rarezva", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Soldimtomva de Tema", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Mazmeshva Moxparem Raxite", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Meshfaz de Docra", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Meshpazxi Gragravaxi", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Meshne Docguezal", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Tomdimfaz de Vavacolma", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Meshdimpazrez de Moxzalpa", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Maztommazgue de Lacol", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Pazdimmazga Fazlaga Rezvacol", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Tomdimva Nela", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Pazdou Maragadou Moxrem", "JOGADOR");
        CRIAR_JOGADOR("Meshum", "Mazmox Magava", "MÉDICO");
        CRIAR_JOGADOR("Meshum", "Meshpazmeshgra de Doucolrezgue", "MÉDICO");
        CRIAR_JOGADOR("Meshum", "Tommeshne Moxguezalte Guemox", "MÉDICO");
        CRIAR_JOGADOR("Meshum", "Dimtommazguo de Docteximox Rala", "MÉDICO");
        CRIAR_JOGADOR("Meshum", "Solla Guolone Palava", "MÉDICO");
        CRIAR_JOGADOR("Mazdoc", "Meshmazzal Moxfaz", "TREINADOR");
        CRIAR_JOGADOR("Mazdoc", "Mazrem Tefaz Docradocne", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Solva Docdocgrala Doclo", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Mazrem Docguocolrem Rezgra", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Soltomdoc Fazmaramox", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Tommazmazmox Moxlora Radoufaz", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Solrem de Xigrafaz Lodou", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Tomrem de Ladou", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Tomtomra de Tefaz Zalfazzalla", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Meshpazsolguo de Doucoldoc Doumavazal", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Meshsoldou de Texizal Laremlafaz", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Solfaz de Fazra Ragama", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Tomdimxi Rezgueremne Lagralazal", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Dimpazguo Macollocol", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Mazrem de Gafazlolo", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Soltompazra Terem", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Meshfaz de Lamafazgue Ladoc", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Mazdimrem Moxmox", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Meshmazne Zaltepa", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Pazmaztomgra de Doulalote Guerague", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Soldimfaz Pamoxnene Docgue", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Solzal Pacolte", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Meshmeshmazdou de Dourezpa Guepama", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Soldimxi Moxlalane", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Meshgra Mafazremlo", "JOGADOR");
        CRIAR_JOGADOR("Mazdoc", "Pazdimmazne de Garem Magra", "MÉDICO");
        CRIAR_JOGADOR("Mazdoc", "Solfaz de Lozal Rezzalvara", "MÉDICO");
        CRIAR_JOGADOR("Mazdoc", "Pazdimdimla Vavazal", "MÉDICO");
        CRIAR_JOGADOR("Mazdoc", "Mazla Lavaxicol Nepazalga", "MÉDICO");
        CRIAR_JOGADOR("Mazdoc", "Mazdimsolgue de Guovaguorez Lavadoula", "MÉDICO");
        CRIAR_JOGADOR("Soltz", "Meshrez de Lamox", "TREINADOR");
        CRIAR_JOGADOR("Soltz", "Mazrez de Lapava Guoxi", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Pazpaztomte de Lazal", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Meshpazrez de Moxraguo", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Meshne Remgraxiva Moxmoxfaz", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Pazdimpazlo Zalne", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Solcol de Manegue Zalne", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Dimgra de Tegamoxrez", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Meshva Lalara", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Maztommeshne de Docte", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Pazte Lodoula", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Mazmeshva Grarem Papagra", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Dimdimmeshfaz de Lava Vagra", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Meshsolmeshra Loraxirem Nexi", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Pazgra Raremva Ladoccolva", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Solsolmazga de Guelo Larezremgra", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Tomsolguo Xivaxiguo Logra", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Mazpazmazla Nezalremxi", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Tomtomma Gravaguo", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Dimdimgue de Palaparez", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Meshdimxi Gane Negranezal", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Dimva Rafaz Zalva", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Meshmazpa de Douga Reztezallo", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Pazrez Gracolgue", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Dimdimrez Lovarez", "JOGADOR");
        CRIAR_JOGADOR("Soltz", "Mazmeshxi de Xinefaz Moxguo", "MÉDICO");
        CRIAR_JOGADOR("Soltz", "Meshsoltommox Guete", "MÉDICO");
        CRIAR_JOGADOR("Soltz", "Soldimfaz Guegradou", "MÉDICO");
        CRIAR_JOGADOR("Soltz", "Meshdoc de Faztedouga Guecoldou", "MÉDICO");
        CRIAR_JOGADOR("Soltz", "Maztomrez de Rarezpane Rezzalxiva", "MÉDICO");
        CRIAR_JOGADOR("Mazte", "Soltomdoc de Guocolne", "TREINADOR");
        CRIAR_JOGADOR("Mazte", "Pazdimguo Fazte Nefazma", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Dimpazdimva de Tega", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Solfaz Vanecol Moxgue", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Mazmazne Guomoxfazla Docva", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Pazdimsolcol Gramamara Tegraremcol", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Solrem de Ravava", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Pazguo Docxigra", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Tomgue de Fazte Rezlo", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Meshsolxi de Remrezdou Zalfazximox", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Mazsolpazmox Collo", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Dimtompazxi Lozalnezal Colmox", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Pazdoc Doccolguezal Douguo", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Pazsolpazpa Zaldoctema", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Mazmazdou Remrezdoc Moxxiga", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Mazpazrez Rava Lologaxi", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Meshdimdimmox Moxra", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Tomsolsolne de Fazlorezxi", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Solmox Fazva Lazalnelo", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Mazrez de Rezradou", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Mazfaz Zalguoteguo", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Solte Madocmoxguo", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Soltomgue de Gamoxguete Colpa", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Maztomsolne de Colguova Xizal", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Solcol Gapadougue", "JOGADOR");
        CRIAR_JOGADOR("Mazte", "Mazmazra de Fazvadou Xilorava", "MÉDICO");
        CRIAR_JOGADOR("Mazte", "Tommeshsolzal Teneguela", "MÉDICO");
        CRIAR_JOGADOR("Mazte", "Dimsolmox de Raramazal", "MÉDICO");
        CRIAR_JOGADOR("Mazte", "Tomdimpazte de Zalremmoxzal", "MÉDICO");
        CRIAR_JOGADOR("Mazte", "Meshgue de Loxi Nedocremga", "MÉDICO");


        CRIAR_JOGADOR("Qoota", "Pazfaz de Raguevagra", "TREINADOR");
        CRIAR_JOGADOR("Qoota", "Pazxi Teva Guedounegue", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Pazcol Zalcoldoufaz Douremlapa", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Pazpazte Fazguedocgra Remrezgueguo", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Mazmeshsoldoc de Radoura", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Meshpazte de Guedocguopa", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Tomzal de Ralaterem Colvapazal", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Tommeshgue Gamarem", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Mazfaz de Pacolnefaz", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Pazdimma de Fazzal Telaguete", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Meshdimne de Zalgra Tezal", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Pazxi Guozalxi", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Dimcol de Mamoxfazxi Gueguo", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Mazpazmazxi Nelodoudoc Pafaz", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Solgue de Docla", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Tommox Fazgara", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Meshrem Docmoxgue Xigue", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Tomdimguo Tecolmox Colxilodou", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Dimdimne Maloremgra Gradou", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Dimxi Radocma", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Meshpazcol de Remlo Guonerem", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Solrem de Nenezalgra", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Dimra Graxiraguo Ralorem", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Meshlo Zalnene Tecolpadou", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Solxi Nelara", "JOGADOR");
        CRIAR_JOGADOR("Qoota", "Soldimrez Varemdoune Graguemoxdou", "MÉDICO");
        CRIAR_JOGADOR("Qoota", "Dimte Douremcol Madou", "MÉDICO");
        CRIAR_JOGADOR("Qoota", "Meshpazmeshzal Nene", "MÉDICO");
        CRIAR_JOGADOR("Qoota", "Tomva de Guelalo", "MÉDICO");
        CRIAR_JOGADOR("Qoota", "Solpa Laguelola Padouxilo", "MÉDICO");
        CRIAR_JOGADOR("Tomra", "Tomra de Fazmamaguo", "TREINADOR");
        CRIAR_JOGADOR("Tomra", "Meshtomgue Fazlo Doudou", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Mazguo Pafazmane", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Pazdimtomlo de Moxzalguo Zalpavaxi", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Solsolpa de Xila Temox", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Meshpazmox Tegraxi", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Meshdimmazmox de Xirezximox Xidougrala", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Qoota de Remlarezxi Xilaxi", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Pazdimsolguo de Loxicolpa Docdocva", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Solva de Remrezpa", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Paztommazcol Nexi Guema", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Tommazmeshva Rezlapava Rezrezfaz", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Mazxi de Remmala Colrezne", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Tomdou Guetete Moxcolraga", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Pazmazsolguo de Madoudoccol", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Dimmazgue Teladou", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Mazdimdimzal de Mate", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Meshtommeshfaz Moxpaguegue Guorala", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Maztomrez de Lacol", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Tommazmeshzal de Laguezallo", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Meshmazsolra de Lorezpa", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Mazsoldimdoc de Rezrarem", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Mazdoc de Rezcol", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Soldimguo de Tega Colterez", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Tomzal Docxi Paguoguocol", "JOGADOR");
        CRIAR_JOGADOR("Tomra", "Dimdimcol Lote Douga", "MÉDICO");
        CRIAR_JOGADOR("Tomra", "Mazsolpazga Lorezfaz", "MÉDICO");
        CRIAR_JOGADOR("Tomra", "Dimsolsollo de Marem Xirem", "MÉDICO");
        CRIAR_JOGADOR("Tomra", "Tomdimdimmox de Paga", "MÉDICO");
        CRIAR_JOGADOR("Tomra", "Pazla Coldou", "MÉDICO");

        CRIAR_JOGADOR("Buunkz", "Dimdimpazne de Tefazrama", "TREINADOR");
        CRIAR_JOGADOR("Buunkz", "Tomla Xilopa Padouguedoc", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Meshdimdimma de Gueguora Padoumox", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Solmazsolzal Remnecolgra", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Pazsoldimte Tevatene Nerez", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Pazla Lozal", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Pazsolmeshne Tegradoczal", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Dimdimpazxi de Negragra Fazdoucol", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Tommeshdou de Docfaz Fazguorezra", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Pazdimga de Doumoxrem", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Paztomtomdou de Graguedoute Moxremvalo", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Paztommeshdoc de Nega Moxpa", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Meshne de Zallacolva", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Pazsollo Teguodoclo", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Tomdimfaz de Lonemox Nedou", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Dimsolmazra de Docgaremzal", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Dimpazrez Lorezdoc Loremma", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Maztomla de Gragrama", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Meshpazsolrem de Temaguo Fazpara", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Dimxi Guedocvadoc", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Soltomguo de Ramalo", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Pazmazrez de Gate Padocgra", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Tomrez Docmoxlafaz", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Mazrem de Grafazma", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Meshpazpazrez de Douvague Moxmoxte", "JOGADOR");
        CRIAR_JOGADOR("Buunkz", "Solpazmazfaz de Grala Matezaldou", "MÉDICO");
        CRIAR_JOGADOR("Buunkz", "Paztomgue de Gramoxrez", "MÉDICO");
        CRIAR_JOGADOR("Buunkz", "Tompa de Rezmazalrem", "MÉDICO");
        CRIAR_JOGADOR("Buunkz", "Pazsolsolzal Lafazgue Xigra", "MÉDICO");
        CRIAR_JOGADOR("Buunkz", "Dimrem de Raremxi Maloguo", "MÉDICO");

        CRIAR_JOGADOR("Fazmol", "Mazmox de Gaguo Fazvanedou", "TREINADOR");
        CRIAR_JOGADOR("Fazmol", "Pazpazpazdou Garemnene", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Mazmeshne Gane Nepa", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Tomtomxi de Lozalguo Docdocguoguo", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Mazva Nerezdocla", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Pazfaz de Lolo", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Tomlo de Ladoczalcol", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Mazzal de Ramoxma", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Tomdimdimma de Laranema Doucol", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Dimla Zallopa Vapadou", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Dimtomrez de Tedoc", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Dimsoldimte de Moxtenerez Marem", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Dimsolmeshpa Lodouguelo", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Tompazmazrem Lozalnexi Nezalneguo", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Meshdimcol de Lora", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Meshdimmeshlo de Docla", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Soldou Marava Lorezxirez", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Meshpazmazma de Granega Remrezfaz", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Meshdimgue Coldoucolgue Raganeva", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Mazmeshmeshra de Graguoxi", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Tomsolmeshrez Pava", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Mazzal Ximox Colpagraxi", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Meshva Docdoc", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Tommazrem Lava", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Mazxi de Grague", "JOGADOR");
        CRIAR_JOGADOR("Fazmol", "Mazsolpazra Moxpaguexi Tegue", "MÉDICO");
        CRIAR_JOGADOR("Fazmol", "Dimfaz Negra", "MÉDICO");
        CRIAR_JOGADOR("Fazmol", "Dimmazga Rezxivara", "MÉDICO");
        CRIAR_JOGADOR("Fazmol", "Meshtompazdoc Maximadou", "MÉDICO");
        CRIAR_JOGADOR("Fazmol", "Tommeshpa de Gaguene", "MÉDICO");

    }

}
